- hosts: all
  become: true
  tasks:
    - name: "Normalmente usado para instalar o python2 para o ansible"
      raw: dnf install epel-release.noarch -y; dnf --enablerepo=epel -y install ansible openssh-clients
    - name: 'Instação de pacotes e denpendências do Master NIS'
      yum:
        name:
          - vim
          - nfs-utils
          - ypserv
          - rpcbind
          - yp-tools
          - httpd
          - autofs
          - whowatch
          - policycoreutils-python-utils.noarch
          - libselinux
          - selinux-policy-mls.noarch
          - mcstrans
          - setroubleshoot
          - setroubleshoot-server
          - setools-console
          - glibc-langpack-pt
        state: latest
    - name: "Definindo o dominio NIS"
      command: ypdomainname empresa.corp.bx
    - name: "Copiando arquivo de configuração do ntp"
      copy:
        src: /media/Backup/Vagrant/Arquivos/trabalho/Configs/etc/chrony.conf
        dest: /etc/chrony.conf
    - name: "Copiando arquivo de configuração do hosts"
      copy:
        src: /media/Backup/Vagrant/Arquivos/trabalho/Configs/etc/hosts
        dest: /etc/hosts
    - name: "Copiando arquivo de configuração do network"
      copy:
        src: /media/Backup/Vagrant/Arquivos/trabalho/Configs/etc/sysconfig/network
        dest: /etc/sysconfig/network
    - name: "Copiando arquivo de configuração do yppasswdd"
      copy:
        src: /media/Backup/Vagrant/Arquivos/trabalho/Configs/etc/sysconfig/yppasswdd
        dest: /etc/sysconfig/network
    - name: "Copiando arquivo de configuração do securenets"
      copy:
        src: /media/Backup/Vagrant/Arquivos/trabalho/Configs/var/yp/securenets
        dest: /var/yp/securenets
    - name: "Inciando o firewalld"
      command: systemctl start firewalld.service
    - name: "habilitando os serviços no firewalld"
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - rpc-bind
        - ntp
        - nfs
        - mountd
    - name: "Habilitando as portas no firewalld"
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 944-951/tcp
        - 944-951/udp
    - name: "Habilitando os serviços no SELinux"
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - nis_enabled
        - domain_can_mmap_files
    - name: habilitando os serviços
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - rpcbind
        - ypserv
        - ypxfrd
        - yppasswdd
        - nis-domainname
        - httpd
        - autofs
        - chronyd
